# Generated by Django 6.0.6 on 2026-06-09 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mod',
            options={'ordering': ['-created_at']},
        ),
    ]
